replicaCount: 2

serviceAccountName: msk-sasl-scram-serviceaccount

image:
  kafkaClientMSK:
    image: garystafford/kafka-client-msk:1.0.0
    pullPolicy: IfNotPresent
  kafkaDemoService:
    image: garystafford/kafka-demo-service:1.1.0-scram
    pullPolicy: IfNotPresent
    ports:
      containerPort: 8080