

kafkaClientMSK:
  serviceAccountName: kafka-client-msk-sasl-scram-serviceaccount
  replicaCount: 1
  image:
    image: garystafford/kafka-client-msk:1.0.1
    pullPolicy: IfNotPresent
kafkaDemoService:
  serviceAccountName: kafka-demo-app-sasl-scram-serviceaccount
  replicaCount: 2
  image:
    image: garystafford/kafka-demo-service:1.1.0-scram
    pullPolicy: IfNotPresent
    ports:
      containerPort: 8080