replicaCount: 2

#serviceAccountName: msk-oidc-serviceaccount
serviceAccountName: msk-sasl-scram-serviceaccount

image:
  image: garystafford/kafka-demo-service:1.1.0-scram
  pullPolicy: IfNotPresent
  ports:
    containerPort: 8080