apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-client
  name: kafka-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-client
  template:
    metadata:
      labels:
        app: kafka-client
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - image: tomcat:jdk16-openjdk
          name: kafka-client
